### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by jorgevinagre** [khendrikse/blinkt-purple-blue#1]
When run from raspbian lite gives an error:
 File "blue_purple.py", line 15
    blinkt.show()
                ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by khendrikse** [comment]
Hey @SirLancelotDuLac thanks for bringing this up :) pulled it through a linter, should be fixed now.
